@baseUrl = http://localhost:3000/api/v1
@password = password123

### 1. Setup Data
# 1a. Login Admin
# @name loginAdmin
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "admin_test@test2.com",
  "password": "{{password}}"
}

###
@adminToken = {{loginAdmin.response.body.data.token}}
@adminId = {{loginAdmin.response.body.data.user.id}}
@adminOrgId = {{loginAdmin.response.body.data.user.organization_id}}

### 1b. Create Manager User
# @name createManager
POST {{baseUrl}}/users
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
    "name": "Multi Project Manager",
    "email": "manager_multi@test.com",
    "organization_id": "{{adminOrgId}}",
    "password": "{{password}}",
    "role": "manager"
}

###
@managerId = {{createManager.response.body.data.id}}

### 1c. Create Member User
# @name createMember
POST {{baseUrl}}/users
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
    "name": "Project Member",
    "email": "member_proj@test.com",
    "organization_id": "{{adminOrgId}}",
    "password": "{{password}}",
    "role": "member"
}

###
@memberId = {{createMember.response.body.data.id}}

### 1d. Create Project A
# @name createProjectA
POST {{baseUrl}}/projects
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "name": "Project Alpha",
  "description": "First project for multi-assignment test"
}

###
@projectAId = {{createProjectA.response.body.data.id}}

### 1e. Create Project B
# @name createProjectB
POST {{baseUrl}}/projects
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "name": "Project Beta",
  "description": "Second project for multi-assignment test"
}

###
@projectBId = {{createProjectB.response.body.data.id}}

### 2. Assignment Tests
### 2a. Assign Manager to Project A
PATCH {{baseUrl}}/users/{{managerId}}/project
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
    "project_id": "{{projectAId}}"
}

### 2b. Assign Manager to Project B (Multi-Assignment Check)
PATCH {{baseUrl}}/users/{{managerId}}/project
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
    "project_id": "{{projectBId}}"
}

### 2c. Assign Member to Project A
PATCH {{baseUrl}}/users/{{memberId}}/project
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
    "project_id": "{{projectAId}}"
}

### 3. Query Tests: Projects based on User
### 3a. Login as Manager
# @name loginManager
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "manager_multi@test.com",
  "password": "{{password}}"
}

###
@managerToken = {{loginManager.response.body.data.token}}

### 3b. Manager: Get All Projects (Should see everything in Org, including A and B)
GET {{baseUrl}}/projects
Authorization: Bearer {{managerToken}}

### 3c. Login as Member
# @name loginMember
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "member_proj@test.com",
  "password": "{{password}}"
}


###
@memberToken = {{loginMember.response.body.data.token}}

### 3d. Member: Get Projects (Should ONLY return Project A)
GET {{baseUrl}}/projects
Authorization: Bearer {{memberToken}}

### 4. Query Tests: Users based on Project
### 4a. Get Users in Project A (Should contain Manager AND Member)
GET {{baseUrl}}/users?project_id={{projectAId}}
Authorization: Bearer {{adminToken}}

### 4b. Get Users in Project B (Should contain ONLY Manager)
GET {{baseUrl}}/users?project_id={{projectBId}}
Authorization: Bearer {{adminToken}}

### 4c. Paginated Users in Project A (Limit 1)
GET {{baseUrl}}/users?project_id={{projectAId}}&limit=1
Authorization: Bearer {{adminToken}}

### 4d. Get manager's projects
GET {{baseUrl}}/projects?user_id={{managerId}}
Authorization: Bearer {{memberToken}}
